apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: MTIzNDU2  # Base64-encoded value - 123456
  JWT_SECRET: Y29tLmdsLmNhcHN0b25lLmhvbWVjb21tZXJjZQ==  # Base64-encoded value - com.gl.capstone.homecommerce
  SPRING_MAIL_PASSWORD: aWVrd2N0bXJqcmdvYm9scw==  # Base64-encoded value - iekwctmrjrgobols
