apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1  # Set to more than 1 for production to ensure high availability
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ranjansharma123/capstone:frontend  # Public image for frontend
        ports:
        - containerPort: 80  # Expose container's port 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000  # Expose service on port 3000
      targetPort: 80  # Forward to container's port 80
      nodePort: 31000  # Set this to a fixed NodePort in the valid range (30000–32767)